/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import classes.Client;
import classes.User;
import controller.Login_Funcionario_Controller;

/**
 *
 * @author PauloR
 */
public class Login_Funcionario extends javax.swing.JFrame {
    private final Login_Funcionario_Controller controller;
    private boolean verificador;

    /**
     * Creates new form Login_Funcionario
     */
    public Login_Funcionario() {
        initComponents();
        controller = new Login_Funcionario_Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Área do Funcionário");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        jButton1.setText("Cadastrar rota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar barco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar funcionario");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user_login = jTextField1.getText();
        String user_password = jTextField2.getText();
        User user = new User();
        // System.out.println(user_login);
        FileInputStream fin = null;
        ObjectInputStream ois = null;
        try{
            System.out.println("a");
            fin = new FileInputStream("sistema_venda_bilhetes_naval/funcionariosCadastrados.txt");
            ois = new ObjectInputStream(fin);
            
            ArrayList<Client> funcionarios = (ArrayList<Client>) ois.readObject();
            // Client cliente = (ArrayList<Client>)in.readObject();
            
            // System.out.println("a");
            // while(true){
                // System.out.println("a");
                
                // try{
                    // cliente = (Client) obj;
                    // ArrayList<Client> funcionarios = (ArrayList<Client>) obj;
                    // System.out.println(cliente.getLogin());
                    for(Client cliente: funcionarios){
                        System.out.println(cliente.getLogin() + cliente.getSenha());
                        // System.out.println(cliente);
                        if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
                            verificador = true;
                            break;
                        }
                        else{
                            verificador = false;
                        }
                }

                    // if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
                    //     verificador = true;
                    // }
                    // else{
                    //     verificador = false;
                    // }
                // }
                // catch(Exception e){
                //     System.out.println("ERROOOOOO");
                //     break;
                // }
            // }
        //     // cliente = (Client) ois.readObject();
        //     // String user_login = view.user_login;
        //     // System.out.println(cliente.getLogin());
        //     // System.out.println(cliente.getSenha());
        //     System.out.println(cliente.getLogin());
        //     // System.out.println(user_login);
        //     // System.out.println(user_password);
        //     // if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
        //     //     verificador = true;
        //     // }
        //     // else{
        //     //     verificador = false;
        //     // }
        //     ois.close();
        //     fin.close();

            
    
        //     // System.out.println(f1.toString());
        //     // System.out.println(d1.toString());
        //     // System.out.println(uea.toString());
        }catch(Exception e){
            // e.printStackTrace();
            System.out.println(1);
        }

        // for(Client cliente: Register.funcionarios){
        //     System.out.println(cliente);
        //     if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
        //         verificador = true;
        //     }
        //     else{
        //         verificador = false;
        //     }
        // }
        


        if(user_login.isEmpty() || user_password.isEmpty()){
            // System.out.println("Preencher");
            JOptionPane.showMessageDialog(null, "Preencha os campos solicitados");
        }
        else if(verificador == true){
            this.controller.goCadastroRotasScreen();
        }
        else{
            JOptionPane.showMessageDialog(null, "Login e senha não cadastrados");
            // System.out.println("OK");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user_login = jTextField1.getText();
        String user_password = jTextField2.getText();
        User user = new User();
        // System.out.println(user_login);
        FileInputStream fin = null;
        ObjectInputStream ois = null;
        try{
            System.out.println("a");
            fin = new FileInputStream("sistema_venda_bilhetes_naval/funcionariosCadastrados.txt");
            ois = new ObjectInputStream(fin);
            
            ArrayList<Client> funcionarios = (ArrayList<Client>) ois.readObject();
            // Client cliente = (ArrayList<Client>)in.readObject();
            
            // System.out.println("a");
            // while(true){
                // System.out.println("a");
                
                // try{
                    // cliente = (Client) obj;
                    // ArrayList<Client> funcionarios = (ArrayList<Client>) obj;
                    // System.out.println(cliente.getLogin());
                    for(Client cliente: funcionarios){
                        System.out.println(cliente.getLogin() + cliente.getSenha());
                        // System.out.println(cliente);
                        if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
                            verificador = true;
                            break;
                        }
                        else{
                            verificador = false;
                        }
                }

                    // if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
                    //     verificador = true;
                    // }
                    // else{
                    //     verificador = false;
                    // }
                // }
                // catch(Exception e){
                //     System.out.println("ERROOOOOO");
                //     break;
                // }
            // }
        //     // cliente = (Client) ois.readObject();
        //     // String user_login = view.user_login;
        //     // System.out.println(cliente.getLogin());
        //     // System.out.println(cliente.getSenha());
        //     System.out.println(cliente.getLogin());
        //     // System.out.println(user_login);
        //     // System.out.println(user_password);
        //     // if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
        //     //     verificador = true;
        //     // }
        //     // else{
        //     //     verificador = false;
        //     // }
        //     ois.close();
        //     fin.close();

            
    
        //     // System.out.println(f1.toString());
        //     // System.out.println(d1.toString());
        //     // System.out.println(uea.toString());
        }catch(Exception e){
            // e.printStackTrace();
            System.out.println(1);
        }

        // for(Client cliente: Register.funcionarios){
        //     System.out.println(cliente);
        //     if(user_login.equals(cliente.getLogin())  && user_password.equals(cliente.getSenha())){
        //         verificador = true;
        //     }
        //     else{
        //         verificador = false;
        //     }
        // }
        


        if(user_login.isEmpty() || user_password.isEmpty()){
            // System.out.println("Preencher");
            JOptionPane.showMessageDialog(null, "Preencha os campos solicitados");
        }
        else if(verificador == true){
            this.controller.goCadastroBarcosScreen();
        }
        else{
            JOptionPane.showMessageDialog(null, "Login e senha não cadastrados");
            // System.out.println("OK");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.controller.goLoginScreen();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.controller.goRegisterFuncionarioScreen();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
